//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string receiver_email { get; set; }
        public System.DateTime sending_time { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
